server:
  port: 5000
  servlet:
    context-path: /passage


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/passage?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver